export const TEST_USER_ID = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee";
export const TEST_EMAIL = "playwright@example.com";
export const TEST_PASSWORD = "Playwright1!";

export const SEED_REPRESENTATIVES = [
  {
    bioguide_id: "S000001",
    first_name: "Hank",
    last_name: "Green",
    official_full_name: "Hank Green",
    chamber: "sen",
    state: "MT",
    district: null,
    party: "Democrat",
    state_rank: "senior",
    birthday: "1980-05-05",
    in_office: true,
  },
  {
    bioguide_id: "S000002",
    first_name: "John",
    last_name: "Green",
    official_full_name: "John Green",
    chamber: "sen",
    state: "IN",
    district: null,
    party: "Democrat",
    state_rank: "junior",
    birthday: "1977-08-24",
    in_office: true,
  },
  {
    bioguide_id: "R000001",
    first_name: "April",
    last_name: "May",
    official_full_name: "April May",
    chamber: "rep",
    state: "IN",
    district: 1,
    party: "Democrat",
    state_rank: null,
    birthday: "1980-04-01",
    in_office: true,
  },
  {
    bioguide_id: "R000002",
    first_name: "Peter",
    last_name: "Petrawicki",
    official_full_name: "Peter Petrawicki",
    chamber: "rep",
    state: "IN",
    district: 2,
    party: "Republican",
    state_rank: null,
    birthday: "1955-06-15",
    in_office: true,
  },
  {
    bioguide_id: "R000003",
    first_name: "Andy",
    last_name: "Skampt",
    official_full_name: "Andy Skampt",
    chamber: "rep",
    state: "IN",
    district: 3,
    party: "Independent",
    state_rank: null,
    birthday: "1992-09-20",
    in_office: true,
  },
  {
    bioguide_id: "R000004",
    first_name: "Miranda",
    last_name: "Beckwith",
    official_full_name: "Miranda Beckwith",
    chamber: "rep",
    state: "IN",
    district: 4,
    party: "Democrat",
    state_rank: null,
    birthday: "1978-11-30",
    in_office: true,
  },
];
